/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class App */

#ifndef _Included_App
#define _Included_App
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     App
 * Method:    reduce
 * Signature: (Ljava/nio/ByteBuffer;ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_App_reduce
  (JNIEnv *, jobject, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
